version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf
