name: Build, Migrate & Seed Laravel App

on:
  push:
    branches:
      - main

jobs:
  laravel-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Docker & Compose versions
        run: |
          docker --version
          docker compose version

      - name: Create .env file
        run: |
          cat <<EOF > .env
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=laravel
          DB_PASSWORD=secret
          EOF

      - name: Build and start Docker containers
        run: docker compose up -d --build

      - name: Install Composer dependencies
        run: docker compose exec -T app composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel app key
        run: docker compose exec -T app php artisan key:generate

      - name: Shut down containers
        if: always()
        run: docker compose down -v
