name: Build and Push Laravel Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ mattoe }}
          password: ${{ dckr_pat__GX6E38tRzp1HEPmNMUpW6X8tKM }}

      - name: Build the Docker image
        run: docker build -t ${{ mattoe }}/laravel-app:latest .

      - name: Push the Docker image
        run: docker push ${{ mattoe }}/laravel-app:latest
