name: Build, Migrate & Seed Laravel App

on:
  push:
    branches:
      - main

jobs:
  laravel-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          APP_NAME=Laravel
          APP_ENV=local
          APP_KEY=
          APP_DEBUG=true
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=db
          DB_PORT=3306
          DB_DATABASE=laravel
          DB_USERNAME=laravel
          DB_PASSWORD=secret
          EOF

      - name: Build and start Docker containers
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for DB to be ready..."
          until docker exec $(docker-compose ps -q db) mysqladmin ping -h"db" --silent; do
            sleep 3
          done
          echo "MySQL is ready!"

      - name: Generate app key
        run: docker-compose exec -T app php artisan key:generate

      - name: Run migrations
        run: docker-compose exec -T app php artisan migrate --force

      - name: Run seeders
        run: docker-compose exec -T app php artisan db:seed --force

      - name: (Optional) Run tests
        run: docker-compose exec -T app php artisan test

      - name: Shut down Docker containers
        if: always()
        run: docker-compose down -v
