name: Laravel CI

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # Add this section
      contents: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Set up environment
        run: cp .env.example .env && php artisan key:generate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Lint code (PHP CodeSniffer)
        run: ./vendor/bin/phpcs --standard=PSR12 app/

      - name: Run tests
        run: php artisan test

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build  # Ensures release only runs if build/test job succeeds
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions: # Grant necessary permissions
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
